'use strict';
const AWS = require('aws-sdk-mock')
const AWS_SDK = require('aws-sdk')
AWS.setSDKInstance(AWS_SDK)
AWS.mock('DynamoDB.DocumentClient', 'put', function (params, callback){
  callback(null, 'successfully put item in database');
});

// tests for createMeeting
// Generated by serverless-mocha-plugin
const mochaPlugin = require('serverless-mocha');
const expect = mochaPlugin.chai.expect;
let wrapped = mochaPlugin.getWrapper('createMeeting', '/src/meetings/meeting.js', 'create_meeting');
const event ={
  "message": "Go Serverless v1.0! Your function executed successfully!",
  "input": {
      "resource": "/test",
      "path": "/test",
      "httpMethod": "POST",
      "headers": {
          "Accept": "*/*",
          "Accept-Encoding": "gzip, deflate, br",
          "Cache-Control": "no-cache",
          "CloudFront-Forwarded-Proto": "https",
          "CloudFront-Is-Desktop-Viewer": "true",
          "CloudFront-Is-Mobile-Viewer": "false",
          "CloudFront-Is-SmartTV-Viewer": "false",
          "CloudFront-Is-Tablet-Viewer": "false",
          "CloudFront-Viewer-Country": "BR",
          "Content-Type": "text/plain",
          "Host": "d76hnqtu0h.execute-api.us-east-1.amazonaws.com",
          "Postman-Token": "7d71446d-d714-4f0c-ab62-585b41ec5b2f",
          "User-Agent": "PostmanRuntime/7.28.0",
          "Via": "1.1 28a30873e1e5b92657cf0bcd1c7e4c84.cloudfront.net (CloudFront)",
          "X-Amz-Cf-Id": "HLozj5eJfdW9wZbLvkbPZnS6wY8S3MHJVW1kryYRhwnV57B34nmoqg==",
          "X-Amzn-Trace-Id": "Root=1-60e4a9d9-41f9fc23037ad817368da5af",
          "X-Forwarded-For": "177.131.189.57, 70.132.44.154",
          "X-Forwarded-Port": "443",
          "X-Forwarded-Proto": "https"
      },
      "multiValueHeaders": {
          "Accept": [
              "*/*"
          ],
          "Accept-Encoding": [
              "gzip, deflate, br"
          ],
          "Cache-Control": [
              "no-cache"
          ],
          "CloudFront-Forwarded-Proto": [
              "https"
          ],
          "CloudFront-Is-Desktop-Viewer": [
              "true"
          ],
          "CloudFront-Is-Mobile-Viewer": [
              "false"
          ],
          "CloudFront-Is-SmartTV-Viewer": [
              "false"
          ],
          "CloudFront-Is-Tablet-Viewer": [
              "false"
          ],
          "CloudFront-Viewer-Country": [
              "BR"
          ],
          "Content-Type": [
              "text/plain"
          ],
          "Host": [
              "d76hnqtu0h.execute-api.us-east-1.amazonaws.com"
          ],
          "Postman-Token": [
              "7d71446d-d714-4f0c-ab62-585b41ec5b2f"
          ],
          "User-Agent": [
              "PostmanRuntime/7.28.0"
          ],
          "Via": [
              "1.1 28a30873e1e5b92657cf0bcd1c7e4c84.cloudfront.net (CloudFront)"
          ],
          "X-Amz-Cf-Id": [
              "HLozj5eJfdW9wZbLvkbPZnS6wY8S3MHJVW1kryYRhwnV57B34nmoqg=="
          ],
          "X-Amzn-Trace-Id": [
              "Root=1-60e4a9d9-41f9fc23037ad817368da5af"
          ],
          "X-Forwarded-For": [
              "177.131.189.57, 70.132.44.154"
          ],
          "X-Forwarded-Port": [
              "443"
          ],
          "X-Forwarded-Proto": [
              "https"
          ]
      },
      "queryStringParameters": null,
      "multiValueQueryStringParameters": null,
      "pathParameters": null,
      "stageVariables": null,
      "requestContext": {
          "resourceId": "vbq1cv",
          "resourcePath": "/test",
          "httpMethod": "POST",
          "extendedRequestId": "CD95-FSkoAMFphg=",
          "requestTime": "06/Jul/2021:19:07:05 +0000",
          "path": "/dev/test",
          "accountId": "120741030969",
          "protocol": "HTTP/1.1",
          "stage": "dev",
          "domainPrefix": "d76hnqtu0h",
          "requestTimeEpoch": 1625598425249,
          "requestId": "355678e2-5269-41c8-9421-60ed04374d97",
          "identity": {
              "cognitoIdentityPoolId": null,
              "accountId": null,
              "cognitoIdentityId": null,
              "caller": null,
              "sourceIp": "177.131.189.57",
              "principalOrgId": null,
              "accessKey": null,
              "cognitoAuthenticationType": null,
              "cognitoAuthenticationProvider": null,
              "userArn": null,
              "userAgent": "PostmanRuntime/7.28.0",
              "user": null
          },
          "domainName": "d76hnqtu0h.execute-api.us-east-1.amazonaws.com",
          "apiId": "d76hnqtu0h"
      },
      "body": "{\r\n    \"meetingId\": \"12093212\",\r\n    \"tag\": \"test\",\r\n    \"start\": \"20-02-2022\"\r\n}",
      "isBase64Encoded": false
  }
}
describe('createMeeting', () => {
  before((done) => {
    done();
  });

  it('implement tests here', async () => {
    const response = await wrapped.run(event);
    expect(response).to.not.be.empty;
  });
});
