'use strict';
const AWS = require('aws-sdk-mock')
const AWS_SDK = require('aws-sdk')
AWS.setSDKInstance(AWS_SDK)

// tests for eventTest
// Generated by serverless-mocha-plugin
const mochaPlugin = require('serverless-mocha');
const expect = mochaPlugin.chai.expect;
let wrapped = mochaPlugin.getWrapper('eventTest', '/src/default/read_event.js', 'handler');

describe('Create meeting', () => {
  before((done) => {
    done();
  });

  it('Correct event', async () => {
    const response = await wrapped.run({});
    expect(response.statusCode).to.be.equal(201);
  });
});
