'use strict';
const AWS = require('aws-sdk-mock')
const AWS_SDK = require('aws-sdk')
AWS.setSDKInstance(AWS_SDK)
AWS.mock('DynamoDB.DocumentClient', 'put', function (params, callback){
  callback(null, 'successfully put item in database');
});

// tests for createMeeting
// Generated by serverless-mocha-plugin
const mochaPlugin = require('serverless-mocha');
const expect = mochaPlugin.chai.expect;
let wrapped = mochaPlugin.getWrapper('createMeeting', '/src/meetings/meeting.js', 'create_meeting');

const fs = require('fs');
const path = require('path');

let rawdata = fs.readFileSync(path.join(process.cwd(), 'test', 'meetings','samples','create_meeting', 'correct.json'));
const event = JSON.parse(rawdata);

describe('createMeeting', () => {
  before((done) => {
    done();
  });

  it('implement tests here', async () => {
    const response = await wrapped.run(event);
    expect(response).to.not.be.empty;
  });
});
